version: '2'
services:
  veilletest-postgresql:
    image: postgres:11.4
    # volumes:
    #     - ~/volumes/jhipster/veilletest/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=veilletest
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
